import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link";
import { client } from "../libs/client";
import { Blog } from "../types/blog";

const inter = Inter({ subsets: ['latin'] })

type Props = {
  blog: Array<Blog>;
};

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blog" });

  return {
    props: {
      blog: data.contents,
    },
  };
};

const Home = ({blog}: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-5 text-center w-full">
        <h1 className="text-xl font-semibold">記事一覧</h1>
        <div >
          <ul>
          {blog.map((blog) => (
            <li key={blog.id}>
              <Link href={`/blog/${blog.id}`}>{blog.title}</Link>
            </li>
          ))}
          </ul>
        </div>
      </div>
    </>
  )
}

export default Home;