import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link";
import { client } from "../libs/client";
import { Blog, Category } from "../types/blog";
import Pagination from '@/components/pagination';

const inter = Inter({ subsets: ['latin'] })

type Props = {
  blog: Array<Blog>;
  totalCount: number;
  category: Array<Category>;
};

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blog", queries: { offset: 0, limit: 5 }});
  const categoryData = await client.get({endpoint: "categories"});

  return {
    props: {
      blog: data.contents,
      totalCount: data.totalCount,
      category: categoryData.contents
    },
  };
};

const Home = ({blog, totalCount, category}: Props) => {
  // console.log(category)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-5 text-center w-full">
        <h1 className="text-xl font-semibold">記事一覧</h1>
        <div >
          <p>
            カテゴリー
          </p>
          <ul className="mb-5">
          {category.map((category) => (
            category && (
            <li key={category.id}>
              <Link href={`/category/${category.id}`}>{category.name}</Link>
            </li>
            )
          ))}
          </ul>
          <p>記事タイトル</p>
          <ul>
          {blog.map((blog) => (
            <li key={blog.id}>
              <Link href={`/blog/${blog.id}`}>{blog.title}</Link>
            </li>
          ))}
          </ul>
        </div>
        <Pagination totalCount={totalCount}/>
      </div>
    </>
  )
}

export default Home;